apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjMU5qZzVORGcxTUN3aWFXRjBJam94TnpVMk9EazBPRFV3ZlEuMXo4ZjUwdGhWRmYyS1BPeV9TMU42NThmdG9udk96SVBHRzVBbnpPUVk5cw==
